name: Submit a Research via a DOI
description: You have a DOI for a research
title: "[Submission/DOI]: "
labels: [submission, doi]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a submission.
  - type: input
    id: doi
    attributes:
      label: DOI
      description: Please provide a DOI
      placeholder: http://doi.org/10.1126/science.1239918
    validations:
      required: true
  - type: input
    id: game
    attributes:
      label: Game
      description: What game is this for?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/captn3m0/boardgame-research/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true